name: Build

on:
  push:
    branches:
      - 'main'
      - 'v*'
    tags:
      - 'v*'
  pull_request:
    branches:
      - 'main'
      - 'v*'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - uses: actions/setup-node@v2
        with:
          node-version: 18.x
      - name: Install
        working-directory: app-miner-xmrig
        run: npm install --legacy-peer-deps
      - name: Build
        working-directory: app-miner-xmrig
        run: npm run build
      - name: Install zip
        uses: montudor/action-zip@v1
      - name: package
        working-directory: dist
        run: zip -qq -r ../app-miner-xmrig.zip .
      - uses: actions/upload-artifact@v2
        with:
          name: app-miner-xmrig
          path: app-miner-xmrig.zip
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: app-miner-xmrig.zip



